name: backtestx
description: A new Flutter project.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0

  # Data & Storage
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  csv: ^6.0.0
  share_plus: ^7.2.1
  universal_html: ^2.2.4
  sqflite_common_ffi_web: ^0.4.2+1

  # Charts
  fl_chart: ^0.65.0
  candlesticks: ^2.1.0

  # Utils
  intl: ^0.19.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  uuid: ^4.2.1
  meta: ^1.12.0

  # File handling
  file_picker: ^8.0.0
  path: ^1.8.3

  # PDF
  pdf: ^3.10.8
  printing: ^5.12.0

  # UI
  flutter_svg: ^2.0.9
  font_awesome_flutter:
    path: ../font_awesome_flutter # Points to a local directory
  supabase_flutter: ^2.10.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  golden_toolkit: ^0.15.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  test: ^1.25.15
  image: ^4.1.0
  sqflite_common_ffi: ^2.3.2
  logger: ^1.4.0
  shared_preferences: ^2.5.3

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/images/png/
    - assets/images/jpg/
    - assets/sample_data/
